import { LocationCategory } from "@/types";
import {
    Library,
    School,
    Coffee,
    Building2,
    FlaskConical,
    Dumbbell,
    ParkingCircle,
    Activity,
    Stethoscope,
    Wrench,
    ShoppingCart,
    Utensils,
    Landmark,
    Store,
    Trees,
    Leaf,
    Baby,
    GraduationCap,
    Microscope,
    Flame,
    DoorOpen,
    Droplets,
    Home,
    Factory,
    Fence,
} from "lucide-react";


export const CategoryIconMap: Record<LocationCategory, any> = {
    classroom: School,
    library: Library,
    cafeteria: Coffee,
    dormitory: Home,
    office: Building2,
    laboratory: FlaskConical,
    lab: FlaskConical,
    research: Microscope,
    sports: Activity,
    gym: Dumbbell,
    parking: ParkingCircle,
    clinic: Stethoscope,
    service: Wrench,
    convenience: ShoppingCart,
    canteen: Utensils,
    restaurant: Utensils,
    auditorium: Landmark,
    admin: Building2,
    shop: Store,
    park: Trees,
    garden: Leaf,
    playground: Baby,
    faculty: GraduationCap,
    power: Flame,
    gate: DoorOpen,
    water: Droplets,
    greenhouse: Factory,
    other_facility: Fence,
    other: Building2,
};
